ALTER TABLE business DROP COLUMN IF EXISTS hours_id;
DROP TABLE IF EXISTS hours;
DROP TYPE IF EXISTS days_of_week;
ALTER TABLE business DROP COLUMN IF EXISTS address_id;
DROP TABLE IF EXISTS address;
DROP TYPE IF EXISTS states;
DROP TABLE IF EXISTS business;
DROP TABLE IF EXISTS category;